### ISSUE TITLE
Sensor Box 2 valve reset command failing consistently

### ISSUE THREAD

**Issue by anushadatar** [newsch/ade-logger#1]
qNov 11 16:53:50 raspberrypi log-and-switch.py[1865]: Traceback (most recent call last):
Nov 11 16:53:50 raspberrypi log-and-switch.py[1865]:   File "/home/pi/ade-logger/log-and-switch.py", line 84, in <module>
Nov 11 16:53:50 raspberrypi log-and-switch.py[1865]:     main()
Nov 11 16:53:50 raspberrypi log-and-switch.py[1865]:   File "/home/pi/ade-logger/log-and-switch.py", line 49, in main
Nov 11 16:53:50 raspberrypi log-and-switch.py[1865]:     valve.connect(port=cfg.valve_port, baudrate=cfg.valve_baud)
Nov 11 16:53:50 raspberrypi log-and-switch.py[1865]:   File "/home/pi/ade-logger/serialdevices.py", line 149, in connect
Nov 11 16:53:50 raspberrypi log-and-switch.py[1865]:     self.reset()
Nov 11 16:53:50 raspberrypi log-and-switch.py[1865]:   File "/home/pi/ade-logger/serialdevices.py", line 215, in reset
Nov 11 16:53:50 raspberrypi log-and-switch.py[1865]:     super().reset()
Nov 11 16:53:50 raspberrypi log-and-switch.py[1865]:   File "/home/pi/ade-logger/serialdevices.py", line 191, in reset
Nov 11 16:53:50 raspberrypi log-and-switch.py[1865]:     assert l & 4
Nov 11 16:53:50 raspberrypi log-and-switch.py[1865]: AssertionError
Nov 11 16:53:51 raspberrypi systemd[1]: logger.service: Main process exited, code=exited, status=1/FAILURE
Nov 11 16:53:51 raspberrypi systemd[1]: logger.service: Failed with result 'exit-code'.

Sensor Box two constantly resets itself upon initialization of the log-and-switch program, this is the resulting exist code present when trying to access the raspi's logs.

**Comment by anushadatar** [comment]
The assert is failing here because of an issue with the limit switch (presumably) as illustrated in the [board firmware guide](https://www.geneseo.edu/~pogo/LabVIEW/Assignments/Demos/UniversalStepperBS1010.pdf).

**Comment by anushadatar** [comment]
Definitely part of the issue is 

The limit switch connector for the motor controller on the second box is wrong - the one I grabbed from the ECE stockroom before leaving is missing a pin. To use the motor controller on the new box, you have two options:

    Get a new connector and splice it in so the X+, X-, and ground pins are connected. I'm not sure what part it is, but anyone at Olin should be able to find them in the stockroom fairly easily. It looks something like the "SWR25X" family of connectors from Sullins, and the relevant crimp looks something like https://www.digikey.com/product-detail/en/sullins-connector-solutions/SWT25X-URTC-S01-UU-UU/S9473CT-ND/2769670.
    Rewire the existing connector to use the Y+ and Y- pins instead, and modify the python code to use the y-axis instead of the x-axis.

**Comment by anushadatar** [comment]
We reconnected the limit switch to use the y positions as well. At this point, the catch is that the firemware specifically only catches +/-Y limit actions with +/-  steps. To account for this, we need to maybe shift the axis every time we check latches? 

TODO explain why the connectors are like this somewhere int he docs

**Comment by anushadatar** [comment]
I wrote a little limit switch testing program, but it seems to be returning 0 always regardless. I tried a workflow as well where i just started up an interactive shell, connected to the valve, and then went through trying to report the latches for each axis config while manually triggering the switch, and it still always returned 0.

**Comment by anushadatar** [comment]
I have an access to a single motor controller and valve and will likely try to write some test code. That being said, validation will require testing with a new set of limit switches and with the motor actually powered up, so  there will be SP21 work related to these tasks.

**Comment by anushadatar** [comment]
Got access to the motor controller power supply associated with a previous board, but there are some issues with the configuration of the power rails. Will return to the lab once I source the appropriate screw driver and then I can hopefully fix the initial connection that powers the valve.

**Comment by anushadatar** [comment]
Testing update: the valve with the broken connector and the currently connected motor (with the USB A cable) can talk to each other, but the goto command doesn't actually move the motor - it makes some sounds and shakes but it fails to actually move. The second motor seems to be moving a little more, 

Also thing I learned is that I need to kill any processes that exist that could be engaging the serial device when trying to do manual tests, adding that to the testing setup script, will add a PR for that change when I am on a computer with 2fac setup already :)

**Comment by anushadatar** [comment]
Have moving the motor currently working with the board BS101RS02 M407-0100 and valve 634412A01 ENG, but no dice so far on returning the latches and getting the appropriate limit switch test output. Also something is wrong with interactive valve test as it doesn't actually ever return the object.

**Comment by anushadatar** [comment]
Okay, leaving this open for now, but it looks like? the errors are in hardware if a configuration works that's here.

**Comment by anushadatar** [comment]
Very gingerly closing this issue for now, with the assumption that it "works" for our setup as of the most recent test, but some serious hardware validation needs to happen to determine which sensor box components behave as expected with our software, which genuinely don't work, and which ones we can fix in software.
