### ISSUE TITLE
Sensor Box 2 MCPC returning no data

### ISSUE THREAD

**Issue by anushadatar** [newsch/ade-logger#2]
It looks like the log-and-switch is getting constant "device returned no data" errors, here is some output from trying to just see what the logger output is:
```
pi@raspberrypi:~/ade-logger$ ./mcpclogger.py /dev/serial/by-id/usb-
usb-FTDI_FT232R_USB_UART_ST13o0a9fm-if00-port0
usb-Prolific_Technology_Inc._USB-Serial_Controller_D-if00-port0
pi@raspberrypi:~/ade-logger$ ./mcpclogger.py /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller_D-if00-port0 
err_num=0       
{'concent': '2615', 'rawconc': '2589', 'cnt_sec': '14856', 'condtmp': '20.1', 'satttmp': '45.1', 'satbtmp': '45.3', 'optctmp': '30.2', 'inlttmp': '23.7', 'smpflow': '344', 'satflow': '342', 'pressur': '1
008', 'condpwr': '245', 'sattpwr': '69', 'satbpwr': '0', 'optcpwr': '29', 'satfpwr': '48', 'exhfpwr': '200', 'fillcnt': '0', 'err_num': '0'}
{'concent': '2632', 'rawconc': '2605', 'cnt_sec': '14948', 'condtmp': '20.2', 'satttmp': '45.1', 'satbtmp': '45.3', 'optctmp': '30.2', 'inlttmp': '23.7', 'smpflow': '344', 'satflow': '342', 'pressur': '1
008', 'condpwr': '246', 'sattpwr': '134', 'satbpwr': '25', 'optcpwr': '59', 'satfpwr': '48', 'exhfpwr': '200', 'fillcnt': '0', 'err_num': '0'}
{'concent': '2676', 'rawconc': '2649', 'cnt_sec': '15178', 'condtmp': '20.1', 'satttmp': '45.2', 'satbtmp': '45.3', 'optctmp': '30.2', 'inlttmp': '23.8', 'smpflow': '343', 'satflow': '342', 'pressur': '1
008', 'condpwr': '246', 'sattpwr': '34', 'satbpwr': '0', 'optcpwr': '29', 'satfpwr': '48', 'exhfpwr': '200', 'fillcnt': '0', 'err_num': '0'}
Traceback (most recent call last):
  File "./mcpclogger.py", line 33, in <module>
    print(m.get_reading(), file=f)
  File "/home/pi/ade-logger/serialdevices.py", line 111, in get_reading
    assert len(resp) > 0, "Device returned no data"
AssertionError: Device returned no data
```
and 
```
ERR=lp
{'concent': '2598', 'rawconc': '2573', 'cnt_sec': '14782', 'condtmp': '20.1', 'satttmp': '45.1', 'satbtmp': '45.3', 'optctmp': '30.2', 'inlttmp': '23.8', 'smpflow': '345', 'satflow': '343', 'pressur': '1
009', 'condpwr': '245', 'sattpwr': '79', 'satbpwr': '0', 'optcpwr': '29', 'satfpwr': '48', 'exhfpwr': '200', 'fillcnt': '0', 'err_num': '0'}
{'concent': '2619', 'rawconc': '2592', 'cnt_sec': '14880', 'condtmp': '20.1', 'satttmp': '45.1', 'satbtmp': '45.3', 'optctmp': '30.2', 'inlttmp': '23.8', 'smpflow': '344', 'satflow': '343', 'pressur': '1
009', 'condpwr': '245', 'sattpwr': '79', 'satbpwr': '0', 'optcpwr': '29', 'satfpwr': '48', 'exhfpwr': '200', 'fillcnt': '0', 'err_num': '0'}
Traceback (most recent call last):
File "./mcpclogger.py", line 33, in
print(m.get_reading(), file=f)
File "/home/pi/ade-logger/serialdevices.py", line 111, in get_reading
assert len(resp) > 0, "Device returned no data"
AssertionError: Device returned no data
```

**Comment by anushadatar** [comment]
See: <https://www.brechtel.com/products-item/mixing-condensation-particle-counter/>

**Comment by anushadatar** [comment]
I added another condition to the get_reading() function associated with the MCPC interface in the serialdevices file such that it would just return 0 (instead of failing outright) when it stops getting readings. With that it prints output values and then prints 0s, indicating that this isn't a problem of intermittent failures (probably) but something that works as expected and then stops working as expected.

**Comment by anushadatar** [comment]
I set it to reconnect and sleep for .5 seconds every iteration (regardless of whether or not the previous iteration fails or succeeds). This ran for about 10 minutes, which I perceive is not long enough to "count" as a fix (especially since all of those connects and reconnects potentially have other side effects) but I will probably try to programmatically implement something like this that resets

Recreate this by running `mcpclogger.py` but replacing the final while loop with the following:
```
while True:
    if time.time() - start > period:
        print("iteration")
        print(m.get_reading(), file=f)
        start = time.time()
        m.connect(args.mcpc_port, args.mcpc_baud)
        time.sleep(0.5)
    time.sleep(0.1)
```
which results in the following output: 
```
iteration
{'concent': '2721', 'rawconc': '2692', 'cnt_sec': '15359', 'condtmp': '20.1', 'satttmp': '45.1', 'sat
btmp': '45.3', 'optctmp': '30.2', 'inlttmp': '21.3', 'smpflow': '342', 'satflow': '342', 'pressur': '
1028', 'condpwr': '240', 'sattpwr': '79', 'satbpwr': '0', 'optcpwr': '38', 'satfpwr': '50', 'exhfpwr'
: '200', 'fillcnt': '0', 'err_num': '0'}
iteration
None
iteration
{'ERR': '8read'}
iteration
{'concent': '2391', 'rawconc': '2370', 'cnt_sec': '13500', 'condtmp': '20.1', 'satttmp': '45.1', 'sat
btmp': '45.2', 'optctmp': '30.3', 'inlttmp': '21.2', 'smpflow': '341', 'satflow': '342', 'pressur': '
1028', 'condpwr': '240', 'sattpwr': '79', 'satbpwr': '25', 'optcpwr': '0', 'satfpwr': '50', 'exhfpwr'
: '200', 'fillcnt': '0', 'err_num': '0'}
iteration
```

**Comment by anushadatar** [comment]
Talked to katya, and we discussed modifying the baudrate to match and also the importance of introducing a delay for serial command output https://pastebin.com/QnMiBy0z
```
import sys, time
import serial
 
def convertCmdToBytes(str_cmd):
  if(str_cmd[-1] != '\r'):
    str_cmd += '\r' # Cmd MUST end in carriage return
  cmd_bytearray = bytes(str_cmd, 'utf-8')
  # Return array of individual byte literals
  individual_bytes = [cmd_bytearray[i:i+1] for i in range(len(cmd_bytearray))]
  return individual_bytes
  
try:
  baudrate = 230400
  ser = serial.Serial('COM5', baudrate=baudrate, timeout=1)
  # cmd = 'usbid\r'
  cmd = 'read\r'
  for b in convertCmdToBytes(cmd):
    ser.write(b)
    time.sleep(0.001) # Delay between sending consecutive bytes
  line = ser.readline()
  print(line)
 
except KeyboardInterrupt:
  print('bye')
  sys.exit(0)
```

**Comment by anushadatar** [comment]
The best task here is likely to create a feature branch for testing with the next time a team member has access to an MCPC.

**Comment by anushadatar** [comment]
Another note to check here is that the baudrate we use isn't always consistent, and its not always consistent with the device. When we are next testing on the MCPC we should ensure there is a specific note to confirm that the baudrates match up.

**Comment by anushadatar** [comment]
This is looking surprisingly good on a short test with a smaller sampling period, which is awesome. I'd like to do a longer test with just the measurements before calling it good though!

**Comment by anushadatar** [comment]
Ran a 24 hour test with this device (and its SD card) in it. Will examine it this evening and update this thread with next steps.

**Comment by anushadatar** [comment]
It looks like it drops about 10 interspersed seconds of data within each minute of data, so I'd like to look into some optimizations for this. The thing I'm more concerned about is that the data file starts at like 3 PM the day we put it out there (CPC logging, in contrast, starts at 8:45 AM), so I'm curious to see what raspi issues might be causing that

**Comment by anushadatar** [comment]
Closing this for now to create more granular issues in both this and the logger-data-analysis repository
